version: '3'
services:
    database:
        image: mariadb:10.3.14-bionic
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
    composer:
        image: composer:1.8.5
        volumes:
            - ./application:${WORKING_DIR}
            - vendor:${WORKING_DIR}/vendor
        working_dir: ${WORKING_DIR}
        command: install --ignore-platform-reqs
    web:
        build:
            context: .
            dockerfile: ./.docker/web/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./application:${WORKING_DIR}
            - vendor:${WORKING_DIR}/vendor
        environment:
            - APACHE_DOCUMENT_ROOT
        depends_on:
            - database
            - composer
volumes:
    vendor:
